[book]
authors = ["Seb Blair"]
title = "GEEN1064 Computing Exercises"
language = "en"
multilingual = false
src = "content"

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/teachingmaterial/GEEN1064_Exercises/"
edit-url-template = "https://github.com/teachingmaterial/GEEN1064_Exercises/edit/master/{path}"

[output.html.print]
enable = false

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2